### ISSUE TITLE
期待大佬更新

### ISSUE THREAD

**Issue by zhoujingfu** [lionet1224/crawler#1]
自学egg，希望老哥更新(^_^)

**Comment by lionet1224** [comment]
哈哈，这段时间太忙了，下个月应该就会开始更新了

**Comment by lionet1224** [comment]
哈哈，这段时间太忙了，下个月应该就会开始更新了 @zhoujingfu 
加油，egg还挺好学的，233

**Comment by zhoujingfu** [comment]
> 哈哈，这段时间太忙了，下个月应该就会开始更新了 @zhoujingfu
> 加油，egg还挺好学的，233
哈哈，好好好
